### ISSUE TITLE
Conflict with VanillaFix

### ISSUE THREAD

**Issue by TrashboxBobylev** [misterplus/PlusTweaks#1]
VanillaFix: 1.0.10-150
PlusTweaks: 1.3.8
Minecraft: 1.12.2
Forge: 14.23.5.2854

Can't load both PlusTweaks and VanillaFix. On removing certificates (MANIFEST.MF, SIGNFILE.SF, SIGNFILE.DSA, MUMFREY.RSA) from PlusTweaks's jar Minecraft is able to load successfully.

Crash stacktrace: [Hastebin](https://hastebin.com/togopibuwo.rb)

**Comment by misterplus** [comment]
The log doesn't really help much since this shouldn't be a signing issue, I'd suggest downgrading VanillaFix and try again, since 1.0.10-150 moved to mixin 0.8, in my test environment VanillaFix 1.0.10-99 worked fine.

**Comment by misterplus** [comment]
Fixed in the latest version, moved to mixin 0.8
